FROM adohaha/fun_ros:jazzy
LABEL maintainer igorzubrycki@gmail.com


USER root

RUN apt-get update -q && \
    apt-get install -y --no-install-recommends python3-bqplot python3-tornado && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER ubuntu
